### ISSUE TITLE
[0.5pt] KANBAN BOARD SETUP

### ISSUE THREAD

**Issue by Felipe-Perez-Ferraro** [Felipe-Perez-Ferraro/RUBY_Capstone#1]
We are a team composed by 2:

- @Felipe-Perez-Ferraro (Team Member: 1)
- @ZabihullahNooriWardak (Team Member: 2) 

Project:
https://github.com/Felipe-Perez-Ferraro/RUBY_Capstone/projects/1

**Comment by codepantha** [comment]
## Hi team 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

<img src="https://media0.giphy.com/media/3o6fJ4vB4lQMSrpwKQ/giphy.gif"/>

## Invalid Code Review Request 🛑 

You have submitted a project, that doesn't have the following 👇 
- Link to your GitHub project
- Information about the number of people in your group
- List of GitHub usernames assigned to each team member

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by KDlamini** [comment]
### Hi team @Felipe-Perez-Ferraro, @ZabihullahNooriWardak  🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on to improve your kanban board according to the requirements. You are almost there! 💪🏾 

## Required Changes ♻️
 
The empty Kanban board is meant to help you start the process of distributing tasks among teammates. You have to manually add each task based on the project requirements. The [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md)  has already divided tasks into `group tasks`, `team member #1` and `team member #2`. Use the points to create tasks; it is up to you how you divide the task into different cards, as long as you do not put two different features into one task card. You can add as many reasonable tasks as you want.

- Ensure that the requirements listed as [group tasks](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md#group-task) have a corresponding card in the Kanban board and have both team members assigned.
- Decide who will be `Team Member #1` and `Team Member #2`. Then make sure requirements from the list for a given team member in the [project requirements divided by team member ](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) file have a corresponding card in the Kanban board.
- Kindly make sure that the number of points for each student (`[Xpt]`) in the card title is allocated. The total points per student must be almost equal (must not have a difference greater than 5).
- Each card should have the corresponding student assigned.
- The cards should have meaningful titles and descriptions based on the points in the project requirements.

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the issue thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new issue for re-reviews. You should use the same issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Felipe-Perez-Ferraro** [comment]
Hello @KDlamini I didn't know it sorry. I made the changes requested

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/7SyGkO0kQWCfnUC47Y/giphy.gif)


# Hi @ZabihullahNooriWardak, @Felipe-Perez-Ferraro  👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Proper kanban board template is used ✔
- All tasks are assigned team members

 ## Required Changes ♻️
- Please make sure all the requirements are assigned for each team member as I noticed team member 2 doesn't have the below requirement assigned:
  - All data should be preserved by saving collections in .json files.
- Kindly make sure to provide descriptions for all the cards 
  ![image](https://github.com/Felipe-Perez-Ferraro/RUBY_Capstone/assets/104968236/928522e3-6d75-4e97-9a35-bc9745ae6685)
- For the requirement "Create a schema.sql file with tables that will be analogical to the structure of the classes that you created" kindly make sure to provide a good description as to which table will be created because there are multiple tables and this could lead to confusion
  ![image](https://github.com/Felipe-Perez-Ferraro/RUBY_Capstone/assets/104968236/057ed9d4-5a38-47eb-aad5-080c6837055b)


## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by V-Blaze** [comment]
Hi @Felipe-Perez-Ferraro, @ZabihullahNooriWardak  

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Kanban board setup correctly 💯
-  All cards are assigned to the correct student👍
-  Tasks distributed equally 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
